
import numpy as np
matrix = np.array([[1,-2,3,4],[5,6,7,-8],[9,-10,11,-12]])
print("Matix Data : \n",matrix)
print("After converting matrix data into Absolute Values : ")
ab_matrix = np.absolute(matrix)
print(ab_matrix)
print("After converting matrix data into Negative Values : ") 
neg_matrix = np.negative(matrix)
print(neg_matrix)
add_column = np.array([[10],[20],[30]])
col_result = np.append(matrix,add_column,axis = 1)
print("After Adding a column to the Matrix : \n",col_result)
add_row = np.array([[13,14,15,16]])
row_result = np.append(matrix,add_row,axis = 0)
print("After adding a row to the Matrix:\n",row_result)
remove_row= np.delete(matrix,1,0)
print("After Deleting row '2' From the Matrix: \n",remove_row) 
remove_column = np.delete(matrix,1,1)
print("After Deleting column '2' From the Matrix: \n",remove_column) 
print("Maximum Value in the Matrix : ",np.max(matrix)) 
print("Minimum Value in the Matrix : ",np.min(matrix))
for i in range(len(matrix)):
print("Maximum Value in row",i+1,":",np.max(matrix[i])) 
print("Sum of all values in a Matrix :",np.sum(matrix))

